create or replace PROCEDURE REMOVEDELIVERIESRUNOFSPECIFICDRONE(droneid NUMBER) AS 
BEGIN
DELETE FROM DELIVERY_RUN WHERE id_delivery_run = REMOVEDELIVERIESRUNOFSPECIFICDRONE.droneid;
END REMOVEDELIVERIESRUNOFSPECIFICDRONE;